### ISSUE TITLE
breaks on \d keys

### ISSUE THREAD

**Issue by jden** [jden/indexed-array#3]
e.g. some object ids are only numbers, which breaks IndexedArray (it thinks it's a regular array index, even though it's obviously too big to be in bounds).

in ES5, max array size is specified as Math.pow(2,32) -1, or 4294967295. For convenience, let's just say that any number longer than 10 character long counts as an indexed property, not a natural array index.

We could also maybe make it an option?

**Comment by junosuarez** [comment]
fixed in indexed-array@1.0.0
